# Generated by Django 4.0.7 on 2024-06-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseuser',
            name='signature',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='signatures/'),
        ),
    ]
